version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: spoke
    volumes:
      - /spoke/postgres:/var/lib/postgresql/data
    networks: 
      - db_net
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    networks: 
      - db_net
  spoke:
    image: sema4texas/spoke
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://spoke:spoke@postgres:5432/spoke
      REDIS_URL: redis://redis:6379
      KNEX_MIGRATION_DIR: /spoke/build/server/migrations/
    # ports:
    #   - 3000:3000
    volumes:
      - ./.env:/Spoke/.env
    networks:
      - reverse_proxy
      - db_net
  nginx:
    depends_on: 
      - spoke
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx
      - /spoke/letsencrypt/:/etc/letsencrypt
    networks:
      - reverse_proxy
    ports:
      - 80:80
      - 443:443

volumes:
  postgres:
  redis:
    external: false
networks: 
  reverse_proxy:
  db_net: